-- ATAT: per-site timezone reference for EDI event locations.
-- One row per distinct edi_events.location code (IMPC office or IATA airport),
-- mapped to the centre's actual IANA zone (site-level, not country).
-- Project: EDGE Leg2 (ubgatxfwpmyaqyfrwias).

create table if not exists public.edi_location_timezone (
  location  text primary key,
  iana_zone text not null,
  kind      text,          -- 'office' | 'airport'
  note      text
);

insert into public.edi_location_timezone (location, iana_zone, kind, note) values
  -- airports (IATA)
  ('AKL','Pacific/Auckland','airport','Auckland'),
  ('BKK','Asia/Bangkok','airport','Bangkok'),
  ('BOM','Asia/Kolkata','airport','Mumbai'),
  ('BRU','Europe/Brussels','airport','Brussels'),
  ('BUD','Europe/Budapest','airport','Budapest'),
  ('CDG','Europe/Paris','airport','Paris CDG'),
  ('CGK','Asia/Jakarta','airport','Jakarta'),
  ('CMB','Asia/Colombo','airport','Colombo'),
  ('CWB','America/Sao_Paulo','airport','Curitiba'),
  ('DEL','Asia/Kolkata','airport','Delhi'),
  ('DOH','Asia/Qatar','airport','Doha'),
  ('DXB','Asia/Dubai','airport','Dubai'),
  ('FRA','Europe/Berlin','airport','Frankfurt'),
  ('GRU','America/Sao_Paulo','airport','Sao Paulo'),
  ('HKG','Asia/Hong_Kong','airport','Hong Kong'),
  ('HND','Asia/Tokyo','airport','Tokyo Haneda'),
  ('ICN','Asia/Seoul','airport','Seoul Incheon'),
  ('IST','Europe/Istanbul','airport','Istanbul'),
  ('JFK','America/New_York','airport','New York JFK'),
  ('JNB','Africa/Johannesburg','airport','Johannesburg'),
  ('KUL','Asia/Kuala_Lumpur','airport','Kuala Lumpur'),
  ('LHR','Europe/London','airport','London Heathrow'),
  ('LIS','Europe/Lisbon','airport','Lisbon'),
  ('LOS','Africa/Lagos','airport','Lagos'),
  ('MEX','America/Mexico_City','airport','Mexico City'),
  ('MNL','Asia/Manila','airport','Manila'),
  ('OTP','Europe/Bucharest','airport','Bucharest Otopeni'),
  ('SIN','Asia/Singapore','airport','Singapore'),
  ('SVO','Europe/Moscow','airport','Moscow Sheremetyevo'),
  ('WAW','Europe/Warsaw','airport','Warsaw'),
  ('YVR','America/Vancouver','airport','Vancouver'),
  ('ZRH','Europe/Zurich','airport','Zurich'),
  -- offices (IMPC)
  ('AEDXBA','Asia/Dubai','office','Dubai'),
  ('AUSYDB','Australia/Sydney','office','Sydney'),
  ('BABNXA','Europe/Sarajevo','office','Banja Luka'),
  ('BDDACA','Asia/Dhaka','office','Dhaka'),
  ('BEBRUA','Europe/Brussels','office','Brussels'),
  ('BRCWBA','America/Sao_Paulo','office','Curitiba'),
  ('BRSAOD','America/Sao_Paulo','office','Sao Paulo'),
  ('BTTHIA','Asia/Thimphu','office','Thimphu'),
  ('CAYVRA','America/Vancouver','office','Vancouver'),
  ('CHATTC','Europe/Zurich','office','Switzerland'),
  ('CHZRHB','Europe/Zurich','office','Zurich'),
  ('CNBJSA','Asia/Shanghai','office','Beijing'),
  ('CNCAND','Asia/Shanghai','office','Guangzhou'),
  ('DEFRAA','Europe/Berlin','office','Frankfurt'),
  ('FRROIC','Europe/Paris','office','Roissy'),
  ('GBCVTA','Europe/London','office','Coventry'),
  ('GBLALA','Europe/London','office','UK'),
  ('GBLONH','Europe/London','office','London'),
  ('HKHKGA','Asia/Hong_Kong','office','Hong Kong'),
  ('HUBUDA','Europe/Budapest','office','Budapest'),
  ('IDJKTC','Asia/Jakarta','office','Jakarta'),
  ('INBOMA','Asia/Kolkata','office','Mumbai'),
  ('INBOMB','Asia/Kolkata','office','Mumbai'),
  ('INBOMC','Asia/Kolkata','office','Mumbai'),
  ('INCCUB','Asia/Kolkata','office','Kolkata'),
  ('INDELB','Asia/Kolkata','office','Delhi'),
  ('JPKWSA','Asia/Tokyo','office','Kawasaki'),
  ('JPTYOA','Asia/Tokyo','office','Tokyo'),
  ('JPTYOB','Asia/Tokyo','office','Tokyo'),
  ('JPTYOC','Asia/Tokyo','office','Tokyo'),
  ('KHPNHA','Asia/Phnom_Penh','office','Phnom Penh'),
  ('KRSELB','Asia/Seoul','office','Seoul'),
  ('LKCMBA','Asia/Colombo','office','Colombo'),
  ('LKCMBE','Asia/Colombo','office','Colombo'),
  ('METGDA','Europe/Podgorica','office','Podgorica'),
  ('MXMEXD','America/Mexico_City','office','Mexico City'),
  ('MYKULA','Asia/Kuala_Lumpur','office','Kuala Lumpur'),
  ('NPKTMA','Asia/Kathmandu','office','Kathmandu'),
  ('NZAKLA','Pacific/Auckland','office','Auckland'),
  ('PHMNLB','Asia/Manila','office','Manila'),
  ('PLWAWA','Europe/Warsaw','office','Warsaw'),
  ('PTLISA','Europe/Lisbon','office','Lisbon'),
  ('PTLISE','Europe/Lisbon','office','Lisbon'),
  ('PTLISR','Europe/Lisbon','office','Lisbon'),
  ('QADOHA','Asia/Qatar','office','Doha'),
  ('ROBUHA','Europe/Bucharest','office','Bucharest'),
  ('ROBUHB','Europe/Bucharest','office','Bucharest'),
  ('ROBUHC','Europe/Bucharest','office','Bucharest'),
  ('RUMOWT','Europe/Moscow','office','Moscow'),
  ('SGSINA','Asia/Singapore','office','Singapore'),
  ('SGSIND','Asia/Singapore','office','Singapore'),
  ('SZMTSA','Africa/Mbabane','office','Manzini'),
  ('THBKKA','Asia/Bangkok','office','Bangkok'),
  ('THBKKB','Asia/Bangkok','office','Bangkok'),
  ('THBKKD','Asia/Bangkok','office','Bangkok'),
  ('TRISTE','Europe/Istanbul','office','Istanbul'),
  ('TWTPEA','Asia/Taipei','office','Taipei'),
  ('USJFKA','America/New_York','office','New York'),
  -- non-standard codes present in the data
  ('BERN','Europe/Zurich','office','Bern'),
  ('PARIS','Europe/Paris','office','Paris')
on conflict (location) do update
  set iana_zone = excluded.iana_zone, kind = excluded.kind, note = excluded.note;

alter table public.edi_location_timezone enable row level security;
drop policy if exists authenticated_select_edi_location_timezone on public.edi_location_timezone;
create policy authenticated_select_edi_location_timezone
  on public.edi_location_timezone for select to authenticated using (true);
